[dependencies]
  futures = '0.3.30'
  getopts = '0.2.21'
  kanal = '0.1.0-pre8'
  rocket = '0.5.1'

  serde = {features = ['derive'], version = "1.0.210" }
  serde_json = {version = "1.0.128", features = []}
  rocksdb = "0.21.0"
  tokio =  { features = ['sync', 'rt', 'rt-multi-thread', 'macros', 'time'], version = "1.40.0" }

[dev-dependencies]
  testcontainers  = '0.15.0'

[package]
  edition = '2021'
  name = 'sizes'
  version = '0.0.1'
